
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJR3JDQUJoVWhaNHN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1ESXhPREUzTXpSYUZ3MHpOREExTXpFeE9ESXlNelJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURFVC8vcm5SY01VdWhsU1l3VmpTSjNOTE56YXBCb3F1NGtBbVh1d05rSkZHRnJiOWFVVTVhb3ErYk0KaXZtK3lUK1FGR1ZHWklhMTZucEc5dG43WDZ6YWQwT2E1ei9BYkZTUWJrdFBVUnVDckRnWVdIZU5SbGtGbTR6UwpXMGwzZEJCVW1FOVJRMTd5MDFEOEYxUk5tM3owL25FbUp1UjZjaVRaVm5ERDFHWUorRWlEa09neUt4ajgrRzNvCmZQOTFGUytkVHF6aTAySFBTZjh1b1NldEp1bFVORDVPNmk1SWNGVUxWNGNSTUpoSkthWXRCa0pnSFpWb2p1bVkKM0ZiMk4zNmVGaWlTdExidFNEWWRqaEk0NzM4aXpRb2VlV056SktoNnErdDFKQkJudEh0OExpWG5uZHRDblFBNApxZXhMTDBySWozVmZDWS9mUlJlNjlNdkFqbFhWQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUcXkyeFREekFkaFNYMkRCY05CREg0RmJ6WWhEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzQreUtmeW9ZZgptZmRUTjVDV0ltUXpNWkZEVXNmVDk2SGhPRVRrYTVhRDhhUWFFcElyd3VPWSsxSFN5dFYwMC9hS0cwSnBQYm8zClFYSTdGRXZubHJuSEZha0tCTm5SWmxlaTdCTmRZZVduVzBOMEgwN3BPYUdPeXlOR0QraG5iL0o2NG11OVZ4RFYKZDV2STJyNFBjZWs3V3FMeG43UDdkYVJjTmk1elY1WVl1T3hpclNnSHFVcDBXNy9sTEZGZ3pTZWhMbFpOWDVySAo4NnhlRHFwYldGWmdISk8xNzJ3ZjdiczRMOWlNV2E2cm5lekM0V0VkM2d2aUcrSTJlZmNwa0VIdDNXNkhMTHVxCmg1S0ZOZ1Q3UDF6NXk5MUVsVUpiOS9jRjExSmJTMVpJZld1QlVhZTRpZTJPaUhYdWpXVkVhVzhpRmdIb3ZESHYKQjRZbWVaSTdZb1FLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://9f65024d-3989-4dea-8c1c-5ec405f1e4a3.cpc1-us-central.linodelke.net:443
  name: lke186128

users:
- name: lke186128-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImdOd2JJYXFCZUFlOFhMTGhkRGRpcTk2eXJrNVk0dEtxNjNyM28xNERpblkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcTdoemYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMjAxZmNiZGItMmM5OC00MjRkLThmZDgtNTY4Y2E5ZWE1YmUzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.PmmBQsEknwzj1J-_O3s2K07uA9D08tJlXBwQWCSvDhenRhcufCxaK6f_cIABfzMOo893oxWOZ1vo6HP6qH7Ucu1Fb1jSI4t92GJSyK7DdzDHZIzzin7vBPoMZRXh09ZmYp1WDxRX4mcS2FlPAIlwf1VB4fRqJeLKcqdIpTmiMRgFatIaAga26M2yXSnbsqTUB0eLmbTMpAwrj8hjbXf3bNVU6AkX7MZqFM-AOGPfad_Qc5OgH2Aw7K_ZgTdmOa9J4w0SpvXUnFMtxiFL5W22F2nFXqa538FthNnvxkUzYK4uBEKu1GS9pWjCRYZd-E8MhOPf-L7yVShHBn5yYCKaig

contexts:
- context:
    cluster: lke186128
    namespace: default
    user: lke186128-admin
  name: lke186128-ctx

current-context: lke186128-ctx