name: Canary Deployment Workflow

on:
  workflow_dispatch:

jobs:
  # Step 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  # Step 2: Canary Deployment
  canary-deployment:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy Canary Release
        run: echo "Deploying canary release to a subset of users"

  # Step 3: Full Production Deployment
  production-deployment:
    runs-on: ubuntu-latest
    needs: canary-deployment
    if: success()
    steps:
      - name: Deploy to Production
        run: echo "Deploying to full production environment"