name: Dynamic Application Security Testing (DAST) with OWASP ZAP

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dast:
    name: DAST with OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask Application
        run: |
          python app.py &
        env:
          COLOR: "blue"

      - name: Wait for Flask Application to Start
        run: sleep 10  # Adjust based on application startup time

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-reports
          docker run --rm \
            -v $(pwd)/zap-reports:/zap/wrk:rw \
            --network="host" \
            zaproxy/zap-stable zap-baseline.py \
            -t http://localhost:5000 \
            -r zap_report.html  # HTML report
        # Use zap_report.html format based on your need

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-reports/zap_report.html
