name: DAST with OWASP ZAP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start the Python application
        run: |
          nohup python app.py &  # Start app in the background
          sleep 5  # Allow time for the app to start

      - name: Run ZAP Baseline Scan
        run: |
          docker run -v "$(pwd):/zap/wrk/:rw" -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://127.0.0.1:5000 \
            -g /zap/wrk/gen.conf \
            -r /zap/wrk/zap_report.html \
            --autooff
      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Report
          path: zap_report.html
