name: Dynamic Application Security Testing (DAST) with OWASP ZAP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dast:
    name: DAST with OWASP ZAP
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask Application
        run: |
          python app.py &
        env:
          COLOR: "blue"  # Environment variable for color, if applicable

      - name: Wait for Flask Application to Start
        run: |
          sleep 10  # Adjust based on startup time of the application

      - name: OWASP ZAP Scan
        uses: zapbot/zap-action@v0.1.0
        with:
          target: 'http://localhost:5000'  # URL of the running Flask application
          cmd_options: '-quick-scan'  # Optional: Use a quick scan for faster results

      - name: Report ZAP Scan Results
        if: always()
        run: |
          cat /zap/wrk/output.json

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
