name: DAST with OWASP ZAP

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dast:
    name: DAST with OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask Application
        run: |
          python app.py &
        env:
          COLOR: "blue"

      - name: Wait for Flask Application to Start
        run: sleep 10  # Adjust based on application startup time

      - name: Create Writable Directory for ZAP Reports
        run: mkdir -p zap-reports

      - name: Run OWASP ZAP Baseline Scan
        run: |
           docker run --rm \
             -v $(pwd)/zap-reports:/zap/wrk:rw \  # Ensure writable directory is mounted
             --network="host" \
             zaproxy/zap-stable zap-baseline.py \
             -t http://localhost:5000 \
             -r /zap/wrk/zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-reports/zap_report.html
