name: Security Scan and Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-and-test:
    name: Set Up and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests/unit

  run-app:
    name: Start Python App
    runs-on: ubuntu-latest
    needs: setup-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start App
        run: |
          nohup python app.py &
        # Wait for the app to start
      - name: Wait for App
        run: sleep 10

  zap-scan:
    name: Run OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    needs: run-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -v ${{ github.workspace }}:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t http://127.0.0.1:5000 \
              -g /zap/wrk/gen.conf \
              -r /zap/wrk/testreport.html
