name: SAST with SonarQube

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          host-url: ${{ secrets.SONARQUBE_URL }}
          login: ${{ secrets.SONARQUBE_TOKEN }}