# name: SCA with Snyk and GitHub Code Scanning

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   snyk-scan:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout Code
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Set Up Python Environment (for a Python project)
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.x'

#       # Step 3: Install Dependencies
#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       # Step 4: Run Snyk to Scan for Vulnerabilities
#       - name: Run Snyk to check for vulnerabilities
#         uses: snyk/actions/python@v1
#         continue-on-error: true # Ensures SARIF upload even if vulnerabilities are found
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#         with:
#           args: --sarif-file-output=snyk.sarif --severity-threshold=high

#       # Step 5: Upload Snyk Report to GitHub Code Scanning
#       - name: Upload result to GitHub Code Scanning
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: snyk.sarif




name: SCA with Snyk for Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

    #   # Step 3: Install Dependencies
    #   - name: Install Dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt

    #   # Step 4: Run Snyk to Scan Dependencies
    #   - name: Run Snyk to check for vulnerabilities
    #     uses: snyk/actions/python@v1.5.0
    #     env:
    #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #     with:
    #       args: --severity-threshold=high

      
      - name: Install Snyk CLI
        run: curl -sL https://static.snyk.io/cli/latest/snyk-linux -o snyk && chmod +x snyk && mv snyk /usr/local/bin/
      - name: Run Snyk Test
        run: snyk test --file=requirements.txt --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  